configMapGenerator:
- name: foxglove-demo
  files:
  - default-layout.json 
- name: vo-scripts
  files:
  - app.py=vo1_app.py
  - config.yaml=vo1_config.yaml
  - td.json=vo1_td.json
generatorOptions:
   disableNameSuffixHash: true
resources:
- zenoh-router.yaml
- mqtt-broker.yaml
- flask-app.yaml
- vo-1_deploy.yaml
- foxglove-zenoh.yaml

