# ====================================
# Vo-tb2 Descriptor
# ====================================
name: vo-tb2
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 30886 
bindingNB:
  bindingModeNB: [H]
  hostname: vo-tb2
  ports:
    httpPort: 30885
  securityNB:
    securityScheme: bearer
    token: token
bindingSB:
  bindingModeSB: [M]
  brokerIP: mqtt://160.85.253.140:30884
databaseConfig:
  # timeseriesDB:
  #   influxDB: enabled
  #   address: "http://wotpy-influxdb-vo-tb2:8086"
  #   dbUser: my-username
  #   dbPass: my-password
  #   dbToken: my-token
  persistentDB:
    SQLite: enabled
genericFunction: [vo_status, device_status]
periodicFunction:
  check: 1000
  read_property_from_tb2: 5000
consumedVOs:
  tb2:
    url: "http://160.85.253.140:30886/tb2"
proxy:
  # propertiesMap:
  #   allAvailableResources: tb2
  actionsMap:
    triggerBringup: tb2
    currentValues: tb2

