# ====================================
# Vo1 Descriptor
# ====================================
name: vo1
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 9090 
bindingNB:
  bindingModeNB: [H]
  hostname: vo1
  ports:
    httpPort: 8080
  securityNB:
    securityScheme: bearer
    token: token
bindingSB:
  bindingModeSB: [M]
  #brokerIP: mqtt://mqttbroker:1883
  securitySB:
      securitySBMQTT:
        securityScheme: basic
        username: user
        password: pass
databaseConfig:
  # timeseriesDB:
  #   influxDB: enabled
  #   address: "http://wotpy-influxdb-vo1:8086"
  #   dbUser: my-username
  #   dbPass: my-password
  #   dbToken: my-token
  persistentDB:
    SQLite: enabled
genericFunction: [vo_status, device_status]
periodicFunction:
  check: 1000
  read_property_from_tb2: 5000
consumedVOs:
  tb2:
    url: "http://ngnix-service/tb2"
proxy:
  propertiesMap:
    allAvailableResources: tb2
  actionsMap:
    triggerBringup: tb2
    currentValues: tb2

